modLoader="javafml"
loaderVersion="[40,)"
license="All rights reserved"
[[mods]]
modId="chromatics"
version="${file.jarVersion}"
displayName="Chromatic Capabilities"
logoFile="chromatics.png"
credits="Thanks to Gorp for a base mod!"
authors="Ovionyx"
description='''
Chromatic Capabilities is a mod that hopes to bring back the use of Create\'s Chromatic Compound and its variants.
Github: https://github.com/Ovionyx/ChromaticCapabilities
Discord: https://discord.gg/fKWWATy3uW
'''
[[dependencies.chromatics]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chromatics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
[[dependencies.chromatics]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.a,)"
    ordering="NONE"
    side="BOTH"
